plugins {
    id 'org.springframework.boot' version '4.0.7' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
    repositories {
        mavenCentral()
    }
}

// subprojects {
//     tasks.withType(Jar).configureEach {
//         doLast {
//             if (project.path.startsWith(":solvers:")) {
//                 copy {
//                     from archiveFile
//                     into rootProject.file("engine/solvers")
//                 }
//             }
//         }
//     }
// }

subprojects {
    tasks.withType(Jar).configureEach {
        doLast {
            if (project.path.startsWith(":solvers:")
                     && project.path != ":solvers:library") {

                def destination =
                        file("${rootProject.projectDir}/engine/solvers")

                copy {
                    from archiveFile
                    into destination
                }

                println "Copied ${archiveFile.get().asFile.name} → engine/solvers/"
            }
        }
    }
}